<?php

/**
 * PluginMicropaymentDebitPaymentDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMicropaymentDebitPaymentDataTable extends PaymentDataTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMicropaymentDebitPaymentDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMicropaymentDebitPaymentData');
    }
}